<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_first">

    <xacro:macro 
        name="link" 
        params="name size color parent:='none' orientation:='0 0 0'"
    >
        <xacro:if value="${parent != 'none'}">
            <joint name="end_${name}_link" type="continuous">
                <parent link="connector_${parent}_link"/>
                <child link="${name}_link"/>
                <origin rpy="${orientation}" xyz="0 0 0"/>
            </joint>
        </xacro:if>

        <link name="${name}_link">
            <visual>
                <geometry>
                    <cylinder length="${size}" radius="${width}"/>
                </geometry>
                <origin rpy="0 0 0"  xyz="0 0 ${size/2.+width}"/>
                <material name="${color}"/>
            </visual>

            <collision>
                <geometry>
                    <cylinder length="${size}" radius="${width}"/>
                </geometry>
                <origin rpy="0 0 0"  xyz="0 0 ${size/2.+width}"/>
            </collision>

            <!-- For gazebo, every link must have inertial -->
            <!--<xacro:if value="${parent != 'none'}">-->
            <inertial>
                <mass value="10"/>
                <inertia ixx="0.4" ixy="0.0" ixz="0.0" 
                         iyy="0.4" iyz="0.0" izz="0.2"/>
            </inertial>
            <!--</xacro:if>-->
        </link>

        <joint name="${name}_rigidity" type="fixed">
            <parent link="${name}_link"/>
            <child link="connector_${name}_link"/>
            <origin xyz="0 0 ${size+width}"/>
        </joint>

        <link name="connector_${name}_link">
            <visual>
                <geometry>
                    <sphere radius="${width}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <material name="${color}"/>
            </visual>

            <collision>
                <geometry>
                    <sphere radius="${width}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
            </collision>

            <!--<xacro:if value="${parent != 'none'}">-->
            <inertial>
                <mass value="10"/>
                <inertia ixx="0.4" ixy="0.0" ixz="0.0" 
                                   iyy="0.4" iyz="0.0"
                                             izz="0.2"/>
            </inertial>
            <!--</xacro:if>-->
        </link>
    </xacro:macro>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <xacro:property name="width" value="0.07" />

    <!-- Used for fixing robot to Gazebo 'base_link' -->
    <link name="world"/>
    <joint name="fixed" type="fixed">
        <parent link="world"/>
        <child  link="base_link"/>
    </joint>

    <xacro:link name="base" 
                size="0.6" color="white"/>

    <xacro:link name="first"  parent="base"   
                orientation="-1. 0 0" 
                size="0.9"  color="black"/>

    <xacro:link name="other" parent="base" 
                orientation="1. 0 0" 
                size="0.5"  color="black"/>

    <xacro:link name="second" parent="first"  
                orientation="0. 1.5 0" 
                size="0.6" color="white"/>

    <xacro:link name="third"  parent="second" 
                orientation="0. 1.5 0" 
                size="0.6" color="black"/>
</robot>
